version: "3.9"

name: ohadii_chlorella_gdb_test

services:
  easy_gdb:
    image: ohadii_chlorella_gdb:new
    container_name: gdb-test
    build:
      context: .
    ports:
      - "8000:80"
    environment:
      # mirror this in DB
      - POSTGRES_USERPW=Ch1llyD0g%
      - POSTGRES_DB=postgres-db
  postgres-db:
    image: ohadii_chlorella_postgres:new
    container_name: postgres-test
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # path to postgres init data
      # - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      # mirror this in easy_gdb
      - POSTGRES_USERPW=Ch1llyD0g%
