version: "3.9"

name: ohadii_chlorella_gdb

services:
  easy_gdb:
    container_name: gdb
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    environment:
      # mirror this in DB
      - POSTGRES_USERPW=Ch1llyD0g%
      - POSTGRES_DB=postgres-db
  postgres-db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # path to postgress init data
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      # mirror this in easy_gdb
      - POSTGRES_USERPW=Ch1llyD0g%
