version: "3.9"

services:
  easy_gdb:
    container_name: ohadii_chlorella_gdb
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      # path to postgress init data
      - ./db_init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USERPW=Ch1llyD0g%
  DB:
    image: postgres
    container_name: DB
    volumes:
          - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
